import { FuseNavigation } from '@fuse/types';

export const navigation: FuseNavigation[] = [
    {
        id: 'dashboards',
        title: 'Dashboard',
        translate: 'NAV.DASHBOARDS',
        type: 'item',
        icon: 'dashboard',
        url: '/apps/dashboard',
    },
    {
        id: 'admins',
        title: 'Manage Admin',
        translate: 'NAV.ADMIN',
        type: 'item',
        icon: 'person',
        url: '/apps/admins',
    },
    {
        id: 'users',
        title: 'Manage User',
        translate: 'NAV.USER',
        type: 'item',
        icon: 'supervised_user_circle',
        url: '/apps/users',
    },
    {
        id: 'institutes',
        title: 'Manage Institute',
        translate: 'NAV.INSTITUTE',
        type: 'collapsable',
        icon: 'school',
        children: [
            {
                id: 'manage-institutes',
                title: 'Institute List',
                translate: 'NAV.INSTITUTE',
                type: 'item',
                url: '/apps/institutes/institutelist',
            },
            {
                id: 'manage-institutes-request',
                title: 'Institute Request',
                translate: 'NAV.INSTITUTEREQUEST',
                type: 'item',
                url: '/apps/institutes/instituterequest',
            },
        ],
    },
    {
        id: 'advert',
        title: 'Manage Affiliate Advert',
        translate: 'NAV.ADVERT',
        type: 'item',
        icon: 'image_search',
        url: '/apps/adverts/advertlist',
        children: [
            {
                id: 'advert',
                title: 'Create Form',
                translate: 'NAV.INSTITUTE',
                type: 'item',
                url: '/apps/adverts/advert',
            },
        ],
    },
    {
        id: 'news',
        title: 'Manage News',
        translate: 'NAV.NEWS',
        type: 'item',
        icon: 'book',
        url: '/apps/news',
    },
    {
        id: 'trivia',
        title: 'Manage Trivia',
        translate: 'NAV.TRIVIA',
        type: 'item',
        icon: 'games',
        url: '/apps/trivias',
    },
    {
        id: 'event',
        title: 'Manage Event',
        translate: 'NAV.EVENT',
        type: 'item',
        icon: 'event',
        url: '/apps/event',
    },
    {
        id: 'txclusive',
        title: 'Manage Txclusive',
        translate: 'NAV.TXCLUSIVE',
        type: 'item',
        icon: 'event',
        url: '/apps/txclusive',
    },
];
